name: Deploy to Donweb Cloud

on:
    push:
        branches:
            - develop
    workflow_dispatch:
jobs:
    deploy_to_develop:
        name: deploy dev
        runs-on: ubuntu-22.04

        steps:
            - name: executing remote ssh commands using ssh key
              uses: appleboy/ssh-action@v1.0.0
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: ${{ secrets.SSH_PORT }}
                script: |
                  cd ${{ secrets.WORK_DIR }} 
                  git fetch 
                  git checkout ${{ secrets.MAIN_BRANCH }} 
                  git pull 
                  npm install 
                  npm i --prefix client
                  npm run build --prefix client
                  exit
