name: Deploy to Donweb Cloud

on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            - name: Echo the message
              run: echo "Hola Santiago"
            - name: Checkout 
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Node
              uses: actions/setup-node@v4
              with: 
                node-version: 18.20.4
            - name: Install
              run: npm i
                