name: Deploy to Donweb Cloud

on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            - name: Echo the message
              run: echo "Hola Santiago"			