name: Deploy to Donweb Cloud

on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            - name: Echo the message    
              run: echo "Hola Santiago"
            - name: Checkout 
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Node
              uses: actions/setup-node@v4
              with: 
                node-version: 18.20.4
            - name: Install server
              run: npm i --no-audit --no-fund --no-optional
            - name: Install client
              run: npm i --prefix client
            - name: Build client
              run: npm run build --prefix client
            - name: Copy ssh
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.DESTINATION_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                port: ${{ secrets.DESTINATION_SSH_PORT }}
                script: |
                  cd /var/www/temp2
                  rm -rf *
                  scp -r . santi@66.97.47.170:/var/www/temp2
                